name: Continuos Integration - Stratify Frontend

on:
  push:
    branches: [ "main", "sprint-1", "sprint-2", "sprint-3" ]
  pull_request:
    branches: [ "main", "sprint-1", "sprint-2", "sprint-3" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install
        working-directory: Stratify

      - name: Build do projeto
        run: npm run build
        working-directory: Stratify
  deploy-vue:
    name: Deploy Vue App
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Remote Server to Known Hosts
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

      - name: Git Pull and Run Vue App on Remote Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            cd /home/ubuntu/apps/API_5SEM_FRONT/Stratify

            git checkout $(git rev-parse --abbrev-ref HEAD)
            git pull origin $(git rev-parse --abbrev-ref HEAD)

            # Instala dependências
            npm install

            # Encerra qualquer processo anterior na porta 5173 (Vite, por ex.)
            fuser -k 5173/tcp || true

            # Executa o servidor Vue em segundo plano
            nohup npm run dev --host 0.0.0.0 > app.log 2>&1 &
          EOF